
# swagger-ui custom path

springdoc:
  swagger:
    ui.path:/swagger-ui.html

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
      
  h2:
    console:
      enabled: true
      path: /h2-console
      
axon:
  serializer:
    general: jackson
